var courses = [
  {
    learnings: [
      { name: "Data Types" },
      { name: "Hoisting" },
      { name: "Loops" },
      { name: "Arrays" },
      { name: "Functions" },
      { name: "Classes" },
      { name: "Object Oriented Programming" },
      { name: "Pillars Of OOP" },
      { name: "Design Patterns" }
    ],
    name: "Intro To Web Development.",
    image: "/assets/img/webdesignsnew .jpeg",
    image1:"/assets/img/webdesings1.webp",
    image2:"/assets/img/webtest.jpg",
    image3:"/assets/img/webcode.jpg",
    image4:"/assets/img/htmlcss.jpg",
    description: "Frontend Engineering is the art of crafting immersive and user-centric experiences on the web, shaping the visual and interactive aspects of websites and applications. Frontend Engineers play a pivotal role in bringing designs to life and ensuring seamless interaction between users and digital platforms.",
    prerequsite: "programing fundamentals.",
    whatsappMessage: "Hi I Want To Enroll In Intro To Web Development.",
    duration: "3 Months.",
    price: "RS. 21,000/Month.",
    programoutline:"84 Lectures, 10 Assignments, 1 Project, 3Quizzes, Mid-term Evalution, Final Evalution.",
    classhours:"10 AM - 12 AM",
    studentage:"16 Years",
    classsize:"15 kidz"
      
  },
  {
    learnings: [
      { name: "Data Types" },
      { name: "Hoisting" },
      { name: "Loops" },
      { name: "Arrays" },
      { name: "Functions" },
      { name: "Classes" },
      { name: "Object Oriented Programming" },
      { name: "Pillars Of OOP" },
      { name: "Design Patterns" }
    ],
    name: "Frontend Engineering.",
    image: "/assets/img/newfront .jpeg",
    image1:"/assets/img/html.png",
    image2:"/assets/img/css.png",
    image3:"/assets/img/javascript.webp",
    image4:"/assets/img/reactjs.png",
    description: "With our expertise in Frontend Engineering, we specialize in transforming concepts into interactive realities. Whether it's designing sleek and responsive layouts, optimizing performance for seamless user interaction, or ensuring cross-browser compatibility for a consistent experience across devices, our team is dedicated to delivering excellence at every step.",
    whatsappMessage: "Hi I Want To Enroll In Frontend Engineering.",
    duration: "6 Months.",
    prerequsite: "intro to web development.",
    price: "RS. 21,000/Month.",
    programoutline:"84 Lectures, 10 Assignments, 1 Project, 3Quizzes, Mid-term Evalution, Final Evalution.",
    classhours:"10 AM - 12 AM",
    studentage:"16 Years",
    classsize:"15 kidz"
  },
  {
    learnings: [
      { name: "Data Types" },
      { name: "Hoisting" },
      { name: "Loops" },
      { name: "Arrays" },
      { name: "Functions" },
      { name: "Classes" },
      { name: "Object Oriented Programming" },
      { name: "Pillars Of OOP" },
      { name: "Design Patterns" }
    ],
    name: "Backend Engineering.",
    image: "/assets/img/newbackend 1.jpeg",
    image1:"/assets/img/codecolor .jpeg",
    image2:"/assets/img/colorsideas.png",
    image3:"/assets/img/lockimage.jpeg",
    image4:"/assets/img/codeimage.jpeg",
    description: "In our Backend Engineering course, we dive deep into the intricacies of server-side development, equipping learners with the skills and knowledge needed to design, build, and maintain powerful backend systems. From setting up server environments and managing databases to implementing APIs and handling authentication, our curriculum covers all aspects of backend development.",
    whatsappMessage: "Hi I Want To Enroll In Backend Engineering.",
    duration: "6 Months.",
    prerequsite: "intro to web development.",
    price: "RS. 21,000/Month.",
    programoutline:"84 Lectures, 10 Assignments, 1 Project, 3Quizzes, Mid-term Evalution, Final Evalution.",
    classhours:"10 AM - 12 AM",
    studentage:"16 Years",
    classsize:"15 kidz",
  },
  {
    learnings: [
      { name: "Data Types" },
      { name: "Hoisting" },
      { name: "Loops" },
      { name: "Arrays" },
      { name: "Functions" },
      { name: "Classes" },
      { name: "Object Oriented Programming" },
      { name: "Pillars Of OOP" },
      { name: "Design Patterns" }
    ],
    name: "Programing Fundamentals.",
    image: "/assets/img/newimagebasic.jpeg",
    image1:"/assets/img/codeimage.jpeg",
    image2:"/assets/img/codecolor .jpeg",
    image3:"/assets/img/lockimage.jpeg",
    image4:"/assets/img/colorsideas.png",
    description: "Whether you're a beginner looking to kickstart your journey into the world of coding or an experienced developer seeking to solidify your understanding of programming fundamentals, our course provides a comprehensive and accessible learning experience tailored to your needs. Join us and embark on your path to becoming a proficient and confident programmer.",
    whatsappMessage: "Hi I Want To Enroll In Programing Fundamentals.",
    duration: "3 Months.",
    prerequsite: "Admission Interview.",
    price: "RS. 21,000/Month.",
    programoutline:"42 Lectures, 10 Assignments, 1 Project, 3Quizzes, Mid-term Evalution, Final Evalution.",
    classhours:"10 AM - 12 AM",
    studentage:"16 Years",
    classsize:"15 kidz",
  }
];
